
import "./globals.css";

import Footer from "@/comonents/Footer/Footer";
import Navbar from "@/comonents/Navbar/Navbar";
import { DarkToLight } from "@/context/ThemContext";

import { Montserrat } from "next/font/google";
const bodyFont = Montserrat({ 
  subsets: ["latin"], 
  weight: ['400', '900'],
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <DarkToLight>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
        </DarkToLight>
        </body>
    </html>
  );
}
